# Generated by Django 2.0.3 on 2018-04-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180406_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
