# Generated by Django 2.0.3 on 2018-04-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
