# Generated by Django 2.0.3 on 2018-04-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
