# Generated by Django 2.0.3 on 2018-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posts_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='location',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
    ]
