# Generated by Django 2.0.3 on 2018-04-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180406_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='location',
            field=models.CharField(blank=True, default='DEFAULT', max_length=200),
        ),
    ]
