# Generated by Django 2.0.3 on 2018-04-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180406_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='location',
        ),
    ]
