# Generated by Django 2.0.3 on 2018-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_posts_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='location',
            field=models.CharField(default='DEFAULT', max_length=200),
        ),
    ]
